DROP TABLE BOOKMARK CASCADE CONSTRAINTS;
DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE DIARY CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE PET CASCADE CONSTRAINTS;
DROP TABLE PLACE CASCADE CONSTRAINTS;
DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

DROP SEQUENCE USER_SEQ;
DROP SEQUENCE DIARY_SEQ;
DROP SEQUENCE PET_SEQ;

CREATE TABLE USERS (
   Users_ID NUMBER NOT NULL,
   User_Name VARCHAR2(255) NOT NULL,
   Phone_Number VARCHAR2(255) NOT NULL,
   Email VARCHAR2(255) NOT NULL,
   Password VARCHAR2(255) NOT NULL,
   PRIMARY KEY(USERS_ID)
);

CREATE TABLE PET (
   Pet_ID NUMBER NOT NULL,
   Users_ID NUMBER NOT NULL, 
   Pet_Name VARCHAR2(255) NOT NULL, 
   Species VARCHAR2(255) NOT NULL,
   Gender VARCHAR2(255) NOT NULL,
   Age NUMBER NOT NULL,
   Introduction VARCHAR2(255),
   PRIMARY KEY(Pet_ID),
   FOREIGN KEY(Users_ID) REFERENCES USERS(Users_ID)
);

CREATE TABLE PLACE 
(
   Place_ID	NUMBER NOT NULL,
   Place_Name	VARCHAR2(512) NOT NULL,
   Category	VARCHAR2(512) NOT NULL,
   City	VARCHAR2(512) NOT NULL,
   Detail_Address VARCHAR2(512) NOT NULL,
   Latitude	DECIMAL(10,7) NOT NULL,
   Longitude DECIMAL(10,7) NOT NULL,
   PRIMARY KEY (Place_ID)
);

CREATE TABLE REVIEW (
   Review_ID NUMBER NOT NULL,
   Users_ID NUMBER NOT NULL,
   Place_ID NUMBER NOT NULL,
   Rating NUMBER NOT NULL,
   Content VARCHAR2(100) NOT NULL,
   Created_Date DATE NOT NULL,
   PRIMARY KEY(Review_ID),
   FOREIGN KEY (Users_ID) REFERENCES USERS(Users_ID),
   FOREIGN KEY (Place_ID) REFERENCES PLACE(Place_ID)
);

CREATE TABLE DIARY( 
   Diary_ID NUMBER NOT NULL,
   Content VARCHAR2(500) NOT NULL,
   Users_ID NUMBER NOT NULL,
   Emotion VARCHAR2(200) NOT NULL,
   Created_Date DATE NOT NULL,
   Place_ID NUMBER NOT NULL,
   PRIMARY KEY (Diary_ID),
   FOREIGN KEY (Users_ID) REFERENCES USERS(Users_ID),
   FOREIGN KEY (Place_ID) REFERENCES PLACE(Place_ID)
);


CREATE TABLE COUPON (
   Coupon_ID NUMBER NOT NULL,
   Users_ID NUMBER NOT NULL,
   Coupon_Name VARCHAR2(255) NOT NULL,
   Discount_Rate DECIMAL(3,2) NOT NULL,
   Category VARCHAR2(100),
   Expired_Date DATE NOT NULL,
   Maximum NUMBER NOT NULL,
   PRIMARY KEY(Coupon_ID),
   FOREIGN KEY(Users_ID) REFERENCES USERS(Users_ID)
);

CREATE TABLE BOOKMARK (
   Users_ID NUMBER NOT NULL,
   Place_ID NUMBER NOT NULL,
   Status NUMBER NOT NULL,
   PRIMARY KEY (USERS_ID, Place_ID),
   FOREIGN KEY (Users_ID) REFERENCES USERS(Users_ID),
   FOREIGN KEY (Place_ID) REFERENCES PLACE(Place_ID)
);

CREATE TABLE EVENT( 
   Event_ID NUMBER NOT NULL,
   Event_Name VARCHAR2(100) NOT NULL,
   Start_Date DATE NOT NULL,
   End_Date DATE NOT NULL,
   Description VARCHAR2(500) NOT NULL,
   Place_ID	NUMBER NOT NULL,
   PRIMARY KEY (Event_ID),
   FOREIGN KEY (Place_ID) REFERENCES PLACE(Place_ID)
);

CREATE TABLE RESERVATION( 
   Reservation_ID NUMBER NOT NULL,
   R_Date DATE,
   Price NUMBER(10, 2),
   Users_ID NUMBER NOT NULL,
   Place_ID NUMBER NOT NULL,
   PRIMARY KEY (Reservation_ID),
   FOREIGN KEY (Users_ID) REFERENCES USERS(Users_ID),
   FOREIGN KEY (Place_ID) REFERENCES PLACE(Place_ID)
);


CREATE SEQUENCE USER_SEQ START WITH 501;
CREATE SEQUENCE DIARY_SEQ START WITH 1501;
CREATE SEQUENCE PET_SEQ START WITH 601;

commit;